### ISSUE TITLE
gpt-4o with Images throws a 431 Request Header Fields Too Large

### ISSUE THREAD

**Issue by krohm** [timoklimmer/powerproxy-aoai#117]
When exchanging gpt-4 vision-preview with gpt-4o we are running into a 431 Request Header Fields Too Large. When running the same POST agains openAI directly it works.

```bash
curl --location 'https://.../openai/deployments/gpt-4o/chat/completions?api-version=2024-06-01'
--header 'Content-Type: application/json'
--header 'api-key: 42...' 
--data '{
    "messages": [ 
        {
            "role": "system", 
            "content": "You are a helpful assistant." 
        },
        {
            "role": "user", 
            "content": [
	            {
	                "type": "text",
	                "text": "Describe this picture:"
	            },
	            {
	                "type": "image_url",
	                "image_url": {
                        "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABQAAAAKUCAIAAADU1gJ7A...
                        aP89xM/oSDR3/CuINP8f4ZKVUxiyAcEAAAAASUVORK5CYII="
                    }
                } 
           ] 
        }
    ],
    "max_tokens": 100, 
    "stream": false 
}'
```

**Comment by timoklimmer** [comment]
Hey @krohm, I have added a test for image requests and was not able reproduce your issue. Are you using the latest version of PowerProxy and its dependencies?

**Comment by timoklimmer** [comment]
As discussed/evaluated, the issue is related to App Service. Not investigating further as you are migrating to Container Apps.

**Comment by codylittle** [comment]
Hey @timoklimmer - we're experiencing same issue on CA behind AGW - any pointers before we start nuking AGW policies?

**Comment by krohm** [comment]
@timoklimmer we have modified an cloned powerproxy.px with this line (thanks @brettnf):
 # filter headers to only include those that are relevant for the request to AOAI
    headers = {key: headers[key] for key in headers if key.lower() in ["api-key", "authorization", "content-type", "accept", "accept-encoding", "user-agent", "cache-control"]}
 
 First Tests are ok, what do you think pushing this into main branch ?

**Comment by timoklimmer** [comment]
Good catch, @codylittle and thanks a lot for the code, @krohm, @brettnf. Sending krohm's problem request incl. 10++ headers still works for me, but I do see a benefit in being able to filter headers. Need to think about it how we can make this as comfortable as possible - given that the set of headers required by AOAI will change over time.

**Comment by codylittle** [comment]
@timoklimmer - from running a quick echo server through AGW, below headers were added.
My recommendation would be to not include any headers that start with `x-`

```
    "x-appgw-trace-id": "",
    "x-forwarded-for": "",
    "x-forwarded-host": "",
    "x-forwarded-port": "80",
    "x-forwarded-proto": "http, https",
    "x-original-host": "",
    "x-original-url": "/api/echo",
    "x-middleware-invoke": "",
    "x-invoke-path": "",
    "x-invoke-query": "",
    "x-invoke-output": "/api/echo"
```

**Comment by timoklimmer** [comment]
I am thinking of adding an optional configuration setting under aoai named "forward_http_header_only_if_matches_regex". If the name of the incoming header matches the regex, the header would be forwarded to AOAI, else not.

For example:
a. to have all headers forwarded: .*
b. to have all x- headers removed: (?!x-)
c. to have all x-headers removed except x-abc: ((?!x-)|x-abc)

Default would be .* to avoid introducing breaking changes, but if deployments like yours need header filtering, it would be possible without having to adjust the source code.

@codylittle @krohm @brettnf What do you think?

**Comment by krohm** [comment]
[heart]         Michael Kroh reacted to your message:
________________________________
From: Timo Klimmer ***@***.***>
Sent: Thursday, October 17, 2024 5:52:29 PM
To: timoklimmer/powerproxy-aoai ***@***.***>
Cc: Michael Kroh ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [timoklimmer/powerproxy-aoai] gpt-4o with Images throws a 431 Request Header Fields Too Large (Issue #117)


Done and available in the lastest release (v0.13.0).

**Comment by codylittle** [comment]
Hey @timoklimmer - can confirm this resolved the issue when removing the `x-` headers. Cheers for getting this rolled in so quickly. Just noting, in the config example you referenced 403 rather than 431

**Comment by timoklimmer** [comment]
Ooops, thanks for the hint. I will correct that.
