### ISSUE TITLE
Failure on token "usage" when streaming

### ISSUE THREAD

**Issue by codylittle** [timoklimmer/powerproxy-aoai#130]
Hey @timoklimmer,

Just a heads up, we've found that when the stream contains the singular token "usage" the `on_data_event_from_target_received` within the plugin base throws a key error.

This is because [L105](https://github.com/timoklimmer/powerproxy-aoai/blob/66c56ef3a4427316ce9aaa1c1a2cebb99be43829/app/plugins/base.py#L105) returns true since `routing_slip["data_from_target"]` is a string.

updating L105 to the below resolves the issue without breaking the `last_seen_usage_object_in_data_event` logic:

```python
if "data_from_target" in routing_slip and "usage" in json.loads(routing_slip["data_from_target"]):
```

To replicate, send the below req to a powerproxy instance
```json
{
    "messages": [
        {
            "role": "system",
            "content": "You are an AI assistant."
        },
        {
            "role": "user",
            "content": "Please say the word usage"
        }
    ],
    "stream": true
}
```

**Comment by timoklimmer** [comment]
Hey @codylittle -- thanks a lot for bringing this up. I have just fixed it. The fix is in the latest release.
