### ISSUE TITLE
List of Azure authorizations required for credential used to deploy

### ISSUE THREAD

**Issue by HerveMignot** [timoklimmer/powerproxy-aoai#60]
Hello,

this is a great job and we are testing PowerProxy for our AI apps deployed.

Do you have the limited list of authorizations (permissions) required for deploying Power Proxy to Azure?
Currently using a (Owner + can grant Contributor) is not enough. I have to use a Owner on the full subscription.

That would be a great addition to the documentation.

Best regards

**Comment by timoklimmer** [comment]
Hi @HerveMignot, thanks for the feedback. Unfortunately, I have no list of minimal roles required, but I have added your info to the deployment script.
