### ISSUE TITLE
Use token consumption from streaming response (once available)

### ISSUE THREAD

**Issue by codylittle** [timoklimmer/powerproxy-aoai#77]
Currently none of the gpt-4-turbo variants are [included](https://github.com/timoklimmer/powerproxy-aoai/blob/main/app/helpers/tokens.py#L37), maybe a prefix based approach similar to that used in [tiktoken](https://github.com/openai/tiktoken/blob/main/tiktoken/model.py#L85) would be best.

**Comment by timoklimmer** [comment]
As I understand, including the gpt-4-turbo variants would not make a difference currently, but the function needs indeed to be updated once GPT-4o is available as API and once we finally get token counts in streaming responses. I let this issue open and will fix it in future.

**Comment by codylittle** [comment]
I'm fairly confident that the 4-turbo variants still utilize the same ChatML formatting as prior models, so no change required there.
My query is more around that given `"gpt-4-turbo"` is not in the dictionary, nor is equal to `"gpt-3.5-turbo-0301"`, it'll raise a `NotImplementedError` exception.

**Comment by timoklimmer** [comment]
Token estimation needs to be updated once we have the usage info in the response. On hold for now.

**Comment by codylittle** [comment]
Hey Timo, I assume this is in reference to OAI [update](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options)?
Interested to see how Azure will implement this for streams cut short from `finish_reason: content_filter`.

**Comment by timoklimmer** [comment]
@codylittle Yes, exactly.

**Comment by codylittle** [comment]
Hey @timoklimmer, just a heads up - the usage stats are available when using GPT-4o on 2024-06-01 (PTUs, AUS East testing). Haven't tested other API versions, but I suspect that others may work too.

```json
{
    "choices": [],
    "created": 1726052028,
    "id": "chatcmpl-A6FGm16a0i6JLfD41vXTb6jX4yOU1",
    "model": "gpt-4o-2024-05-13",
    "object": "chat.completion.chunk",
    "system_fingerprint": "fp_80a1bad4c7",
    "usage": {
        "completion_tokens": 19,
        "prompt_tokens": 140,
        "total_tokens": 159
    }
}
```

**Comment by timoklimmer** [comment]
Thanks @codylittle - I will take a look into it.

**Comment by timoklimmer** [comment]
Hey @codylittle, I have updated the code. Whenever there are token infos in the streaming response, these will be taken, else we fallback to the estimated tokens. I will create a new release in a moment.
