### ISSUE TITLE
Whisper support

### ISSUE THREAD

**Issue by krohm** [timoklimmer/powerproxy-aoai#97]
Hi, Ihave tried to include the whisper model into my powerproxy setup. But if fails with an internal error. I do not see anything else in the Logs. Does anyone tried powerproxy with whisper?

```
from openai import AzureOpenAI

audio_file= open("TalkForAFewSeconds16.wav", "rb")

client = AzureOpenAI(
    api_key = "...",
    api_version="2024-02-01",
    azure_endpoint="https://powerproxy.world/")
result=client.audio.translations.create( file=audio_file,model="whisper")


print (result)
```

Same code with Azure OAI Endpoint works

**Comment by timoklimmer** [comment]
Hi @krohm, Whisper is not supported (yet?) but I can take a look into it.

**Comment by timoklimmer** [comment]
Hi @krohm, there was problem related to token counting because Whisper does not have a concept of tokens. I have just submitted a fix, which will be in the next release to come out soon.
